### ISSUE TITLE
kissmanga-downloader-master_downloader_1 exited with code 1

### ISSUE THREAD

**Issue by member112** [bmzhao/kissmanga-downloader#12]
C:\.....\Downloads\kissmanga-downloader-master>docker-compose up
kissmanga-downloader-master_selenium_1 is up-to-date
Starting kissmanga-downloader-master_downloader_1 ... done                                                              Attaching to kissmanga-downloader-master_selenium_1, kissmanga-downloader-master_downloader_1
selenium_1    | --LOG 01:53:26:460754600 Stopping supervisord to support docker restart...
selenium_1    | -- INFO: Docker Img. Version: 3.141.59-318
selenium_1    | -- INFO: Chrome..... Version: 77.0.3865.75
selenium_1    | -- INFO: Firefox.... Version: 69.0
selenium_1    | -- INFO: Using Selenium.....: 3.141.59
selenium_1    | -- WARN: wait-xvfb.sh failed! for DISPLAY=:64
selenium_1    | -- WARN: DISPLAY=:64 is taken, searching for another...
selenium_1    | -- INFO: Possible free DISPLAY=:57
selenium_1    | -- WARN: wait-xvfb.sh failed! for DISPLAY=:57
selenium_1    | -- WARN: DISPLAY=:57 is taken, searching for another...
selenium_1    | -- INFO: Possible free DISPLAY=:59
selenium_1    | ***************** BEGIN: Data Processing Agreement *****************
selenium_1    | By using this software you agree that the following non-PII
selenium_1    | (non personally identifiable information) data will be collected,
selenium_1    | processed and used by Docker-selenium for the purpose of improving
selenium_1    | our test infrastructure tools. Anonymisation with respect of the IP
selenium_1    | address means that only the first two octets of the IP address are
selenium_1    | collected. See the complete license at:
selenium_1    | https://github.com/elgalu/docker-selenium/blob/master/LICENSE.md
selenium_1    | ****************** END: Data Processing Agreement ******************
selenium_1    | supervisord --version=4.0.0.dev0
selenium_1    | 2019-09-30 01:53:38,039 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing
selenium_1    | 2019-09-30 01:53:38,039 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
selenium_1    | 2019-09-30 01:53:38,040 INFO Included extra file "/etc/supervisor/conf.d/selenium-multinode.conf" during parsing
selenium_1    | 2019-09-30 01:53:38,041 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-chrome.conf" during parsing
selenium_1    | 2019-09-30 01:53:38,041 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-firefox.conf" during parsing
selenium_1    | 2019-09-30 01:53:38,042 INFO Included extra file "/etc/supervisor/conf.d/video-rec.conf" during parsing
selenium_1    | 2019-09-30 01:53:38,042 INFO Included extra file "/etc/supervisor/conf.d/vnc.conf" during parsing
selenium_1    | 2019-09-30 01:53:38,042 INFO Included extra file "/etc/supervisor/conf.d/xmanager.conf" during parsing
selenium_1    | 2019-09-30 01:53:38,042 INFO Included extra file "/etc/supervisor/conf.d/xterm.conf" during parsing
selenium_1    | 2019-09-30 01:53:38,232 INFO RPC interface 'supervisor' initialized
selenium_1    | 2019-09-30 01:53:38,233 INFO RPC interface 'supervisor' initialized
selenium_1    | 2019-09-30 01:53:38,234 INFO supervisord started with pid 194
selenium_1    | 2019-09-30 01:53:39,241 INFO spawned: 'xmanager' with pid 197
selenium_1    | 2019-09-30 01:53:39,255 INFO spawned: 'vnc' with pid 198
selenium_1    | 2019-09-30 01:53:39,263 INFO spawned: 'selenium-hub' with pid 199
selenium_1    | 2019-09-30 01:53:39,269 INFO spawned: 'selenium-node-chrome' with pid 200
selenium_1    | 2019-09-30 01:53:39,279 INFO spawned: 'selenium-node-firefox' with pid 201
selenium_1    | 2019-09-30 01:53:39,301 INFO spawned: 'xterm' with pid 207
selenium_1    | 2019-09-30 01:53:39,305 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1    | 2019-09-30 01:53:39,307 INFO success: xterm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1    | 2019-09-30 01:53:41,258 INFO success: xmanager entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
selenium_1    | 2019-09-30 01:53:41,258 INFO success: vnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
selenium_1    | 2019-09-30 01:53:42,339 INFO success: selenium-node-chrome entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
selenium_1    | 2019-09-30 01:53:42,339 INFO success: selenium-node-firefox entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
selenium_1    | Trapped SIGTERM/SIGINT/x so shutting down supervisord gracefully...
selenium_1    | ***************** BEGIN: Data Processing Agreement *****************
selenium_1    | By using this software you agree that the following non-PII
selenium_1    | (non personally identifiable information) data will be collected,
selenium_1    | processed and used by Docker-selenium for the purpose of improving
selenium_1    | our test infrastructure tools. Anonymisation with respect of the IP
selenium_1    | address means that only the first two octets of the IP address are
selenium_1    | collected. See the complete license at:
selenium_1    | https://github.com/elgalu/docker-selenium/blob/master/LICENSE.md
selenium_1    | ****************** END: Data Processing Agreement ******************
selenium_1    | 2019-09-30 09:10:10,090 INFO stopped: xmanager (exit status 0)
selenium_1    | 2019-09-30 09:10:10,090 INFO stopped: selenium-hub (terminated by SIGTERM)
selenium_1    | 2019-09-30 09:10:10,095 INFO waiting for vnc to stop
selenium_1    | 2019-09-30 09:10:10,095 INFO waiting for selenium-node-chrome to stop
selenium_1    | 2019-09-30 09:10:10,095 INFO waiting for selenium-node-firefox to stop
selenium_1    | 2019-09-30 09:10:10,095 INFO waiting for xterm to stop
selenium_1    | 2019-09-30 09:10:10,102 INFO stopped: vnc (exit status 0)
selenium_1    | 2019-09-30 09:10:10,120 INFO stopped: selenium-node-firefox (exit status 137)
selenium_1    | 2019-09-30 09:10:10,124 INFO stopped: selenium-node-chrome (exit status 137)
selenium_1    | 2019-09-30 09:10:12,159 INFO waiting for xterm to stop
selenium_1    | 2019-09-30 09:10:12,199 INFO stopped: xterm (exit status 150)
selenium_1    | 2019-09-30 09:10:12,199 WARN received SIGTERM indicating exit request
selenium_1    | --LOG 09:10:20:930023200 Stopping supervisord to support docker restart...
selenium_1    | -- INFO: Docker Img. Version: 3.141.59-318
selenium_1    | -- INFO: Chrome..... Version: 77.0.3865.75
selenium_1    | -- INFO: Firefox.... Version: 69.0
selenium_1    | -- INFO: Using Selenium.....: 3.141.59
selenium_1    | ***************** BEGIN: Data Processing Agreement *****************
selenium_1    | By using this software you agree that the following non-PII
selenium_1    | (non personally identifiable information) data will be collected,
selenium_1    | processed and used by Docker-selenium for the purpose of improving
selenium_1    | our test infrastructure tools. Anonymisation with respect of the IP
selenium_1    | address means that only the first two octets of the IP address are
selenium_1    | collected. See the complete license at:
selenium_1    | https://github.com/elgalu/docker-selenium/blob/master/LICENSE.md
selenium_1    | ****************** END: Data Processing Agreement ******************
selenium_1    | supervisord --version=4.0.0.dev0
selenium_1    | 2019-09-30 09:10:23,672 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing
selenium_1    | 2019-09-30 09:10:23,672 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
selenium_1    | 2019-09-30 09:10:23,673 INFO Included extra file "/etc/supervisor/conf.d/selenium-multinode.conf" during parsing
selenium_1    | 2019-09-30 09:10:23,673 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-chrome.conf" during parsing
selenium_1    | 2019-09-30 09:10:23,673 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-firefox.conf" during parsing
selenium_1    | 2019-09-30 09:10:23,673 INFO Included extra file "/etc/supervisor/conf.d/video-rec.conf" during parsing
selenium_1    | 2019-09-30 09:10:23,673 INFO Included extra file "/etc/supervisor/conf.d/vnc.conf" during parsing
selenium_1    | 2019-09-30 09:10:23,674 INFO Included extra file "/etc/supervisor/conf.d/xmanager.conf" during parsing
selenium_1    | 2019-09-30 09:10:23,674 INFO Included extra file "/etc/supervisor/conf.d/xterm.conf" during parsing
selenium_1    | 2019-09-30 09:10:23,688 INFO RPC interface 'supervisor' initialized
selenium_1    | 2019-09-30 09:10:23,689 INFO RPC interface 'supervisor' initialized
selenium_1    | 2019-09-30 09:10:23,689 INFO supervisord started with pid 147
selenium_1    | 2019-09-30 09:10:24,693 INFO spawned: 'xmanager' with pid 150
selenium_1    | 2019-09-30 09:10:24,697 INFO spawned: 'vnc' with pid 151
selenium_1    | 2019-09-30 09:10:24,702 INFO spawned: 'selenium-hub' with pid 152
selenium_1    | 2019-09-30 09:10:24,708 INFO spawned: 'selenium-node-chrome' with pid 153
selenium_1    | 2019-09-30 09:10:24,712 INFO spawned: 'selenium-node-firefox' with pid 154
selenium_1    | 2019-09-30 09:10:24,715 INFO spawned: 'xterm' with pid 155
selenium_1    | 2019-09-30 09:10:24,742 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1    | 2019-09-30 09:10:24,742 INFO success: xterm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1    | 2019-09-30 09:10:26,792 INFO success: xmanager entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
selenium_1    | 2019-09-30 09:10:26,792 INFO success: vnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
selenium_1    | 2019-09-30 09:10:27,717 INFO success: selenium-node-chrome entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
selenium_1    | 2019-09-30 09:10:27,718 INFO success: selenium-node-firefox entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
downloader_1  | Waiting for selenium container to start up...
downloader_1  | Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@66480dd7}], required capabilities = Capabilities [{}]
downloader_1  | Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
downloader_1  | System info: host: '17ce6be554cb', ip: '172.18.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.184-linuxkit', java.version: '1.8.0_111'
downloader_1  | Driver info: driver.version: RemoteWebDriver
downloader_1  |         at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
downloader_1  |         at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
downloader_1  |         at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
downloader_1  |         at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
downloader_1  |         at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
downloader_1  |         at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
downloader_1  |         at KissMangaComDownloader.<init>(KissMangaComDownloader.java:67)
downloader_1  |         at KissMangaComDownloader.main(KissMangaComDownloader.java:243)
kissmanga-downloader-master_downloader_1 exited with code 1

**Comment by jpb25** [comment]
same issue

**Comment by teamtaken** [comment]
same issue , to elaborate , first time i ran the code "sudo docker-compose up" everything ran smoothly , it even showed status bars for download tracking , at the end it said ".......exited with code 1". it created an output folder which had only root access (folder had a lock sign on it), the folder was empty. Next i tried to run the command " sudo make run" and this time there was no download status bars , it directly exited to "........exited with code 1". It created another empty output folder which again had root access.

**Comment by RicardoPhilippe** [comment]
Same issue here =/
